version: "3.8"
services:
  dev_env:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dev_env
    hostname: dev_env
    volumes:
      - ./workspace:/workspace:rshared
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/miversen/.ssh/id_rsa:/config/id_rsa
      - /home/miversen/.ssh/id_rsa.pub:/config/id_rsa.pub
      - /home/miversen/.ssh/config:/config/ssh_config
      - /home/miversen/.dev_env_mux.sock:/root/.dev_env_mux.sock
      - root:/root/
    image: miversen33/dev_env

volumes:
  root:
