# Theme (https//github.com/tyrannicaltoucan/vim-deep-space)
[colors.primary]
background = '#1b202a'
foreground = '#9aa7bd'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#232936'
cursor = '#51617d'

# Normal colors
[colors.normal]
black = '#1b202a'
red = '#b15e7c'
green = '#709d6c'
yellow = '#b5a262'
blue = '#608cc3'
magenta = '#8f72bf'
cyan = '#56adb7'
white = '#9aa7bd'

# Bright colors
[colors.bright]
black = '#232936'
red = '#b3785d'
green = '#709d6c'
yellow = '#d5b875'
blue = '#608cc3'
magenta = '#c47ebd'
cyan = '#51617d'
white = '#9aa7bd'

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
opacity = 0.9
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"

[font]
size = 12
[font.normal]
family = "JetBrains Mono Nerd Font"
# family = "Fira Code"
style = "Normal"

[cursor.style]
shape = "Beam"
blinking = "On"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
]
