name: Dev Env Image Creator

on:
  workflow_dispatch:
  push:
    paths:
      - docker/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build docker --file docker/Dockerfile --tag miversen33/dev_env:$(date +%s) --tag miversen33/dev_env:latest
