name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build docker --file Dockerfile --tag miversen33/dev_env:$(date +%s) --tag miversen33/dev_env:latest
